version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  nextjs:
    build: ./frontend
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver

  dotnetapi:
    build: ./backend
    container_name: dotnetapi
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver

volumes:
  sqlvolume:
